apiVersion: db.shasan.com/v1
kind: DbWatcher
metadata:
  name: my-db-watcher
  namespace: default
spec:
  Name: "mysql"
  Host: "127.0.0.1"
  Port: "3306"
  DatabaseName: "mydatabase"
  Username: "admin"
  Password: "securepassword"
  BackupDestType: "local"
  BackupDestPath: "/backups"
  BackupDestName: "db-backup-2024"
